on:
  workflow_call:
name: metrics pipeline
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
          echo "Ambiente do deploy ${{ env.environment }}"
          echo "RUN ID $GITHUB_RUN_ID"
          echo "REPO NAME: $GITHUB_REPOSITORY"
          projeto=$(echo "$GITHUB_REPOSITORY") | cut -d "/" -f 2
          projeto=${GITHUB_REPOSITORY##*/}

          echo "Projeto: $projeto"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Status: $GITHUB_RUN_STATUS"
          echo "Usuario: $GITHUB_TRIGGERING_ACTOR"
 
          
          echo "POST API"
          if curl - s - k - X 'GET'   'https://192.168.0.92:32768/api/Changes/ValidaChange?id=1' - H 'accept: text/plain' | grep - q 'GMUD autorizada'; then
              echo "POST Metrics OK"
              exit 0
          fi
           else
             echo -e "\033[32m\033[1m GMUD não autorizada \033[0m"
             exit 1
          fi               
