on:
  workflow_call:
name: metrics pipeline
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
          echo "deploy ambiente"  $snowuser
          echo "Buildnumber" # 
          echo "ambiente do deploy ${{ env.environment }}"
          echo "RUN ID $GITHUB_RUN_NUMBER"
          echo "REPO NAME: $GITHUB_REPOSITORY"
          projeto=$(echo "$GITHUB_REPOSITORY") | cut -d "/" -f 2
          projeto=${GITHUB_REPOSITORY##*/}

          echo "Projeto: $projeto"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Status: $GITHUB_RUN_STATUS"
 
          
          echo "POST API"
          if curl -k -X 'POST' \
                    'https://192.168.0.92:32768/api/Evento' -H 'accept: text/plain' -H 'Content-Type: application/json' \
                    -d '{
                          "buildId": "'$GITHUB_RUN_NUMBER'",
                          "nomeJob": "'$projeto'",
                          "usuario": "teste",
                          "ambiente": "${{ env.environment }}",
                          "statusRun": "sucess",
                          "branch": "'$GITHUB_REF_NAME'"}' ;then
              echo "POST Metrics OK"
              exit 0
          fi
           else
             echo -e "\033[32m\033[1m Erro Post Metrics"
             exit 1
          fi               


