on:
  workflow_call:
name: metrics pipeline
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
          echo "deploy ambiente"  $snowuser
          echo "Buildnumber" # 
          echo "ambiente do deploy ${{ env.environment }}"
          
          
          echo "POST API"
          if curl -k -X 'POST' \
                    'https://192.168.0.92:32768/api/Evento' -H 'accept: text/plain' -H 'Content-Type: application/json' \
                    -d '{
                          "buildId": "1111",
                          "nomeJob": "teste",
                          "usuario": "teste",
                          "ambiente": "${{ env.environment }}",
                          "statusRun": "sucess",
                          "branch": "master"}' ;then
              echo "POST Metrics OK"
              exit 0
          fi
           else
             echo -e "\033[32m\033[1m Erro Post Metrics"
             exit 1
          fi               


