name: ci-cd-csharp
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      Gmud:
        type: string
      environment:
        required: true
        type: string
      namespace:
        required: true
        type: string  

jobs:
    pipeline-build-dev:
      runs-on: homolog
      if: ${{ github.event.inputs.environment == 'dev' }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
